<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-11 21:31
=======
# Generated by Django 5.2.8 on 2025-11-11 00:49
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
# Generated by Django 5.2.8 on 2025-11-11 00:49
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
<<<<<<< HEAD
                ('tarefa', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('feito', models.BooleanField(default=False)),
=======
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
