# Generated by Django 4.2.26 on 2025-11-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefamodel',
            old_name='nome',
            new_name='tarefa',
        ),
    ]
