# Generated by Django 4.2.26 on 2025-11-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefamodel_prazo_final_alter_tarefamodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefamodel',
            name='descricao',
        ),
    ]
