# Generated by Django 4.2.26 on 2025-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_remove_tarefamodel_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
