"""
Django settings for projeto project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
<<<<<<< HEAD
SECRET_KEY = 'django-insecure-l621tp2*3t2edvoz=-%%rr!ts($nt$b)t0fw(b_6th3s@)vvdt'
=======
SECRET_KEY = 'django-insecure-#!)@ysg3t4z=4b3nf)az-^rqjc_p(_dgrdp2cxdgvnbzl2gl%1'
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
SECRET_KEY = 'django-insecure-#!)@ysg3t4z=4b3nf)az-^rqjc_p(_dgrdp2cxdgvnbzl2gl%1'
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
<<<<<<< HEAD

#criação dos apps

    'tarefas',
    'bootstrap5',
    'users',
=======
    'tarefas'
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
    'tarefas'
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
<<<<<<< HEAD
        'DIRS': [],
=======
        'DIRS': [BASE_DIR/'templates'],
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
        'DIRS': [BASE_DIR/'templates'],
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

<<<<<<< HEAD
<<<<<<< HEAD
#foi alterado para pt-br, para hora não aparecer como p.m ou a.m
=======
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
<<<<<<< HEAD
<<<<<<< HEAD

LOGIN_URL = 'login'

#instalação do bootstrap
BOOTSTRAP5 = {
    'include_jquery': True
}
=======
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
=======
>>>>>>> f6c29825cea240311fcef022460126e90bbca9fb
